version: '3'

services:
  app:
    container_name: nextjs-app
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:delegated
      - bashhistory:/commandhistory:delegated
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    command: ["docker/app/startup.sh"]
volumes:
  node_modules:
  bashhistory:
